### ISSUE TITLE
Add all basic editing functions to "Edit" menu

### ISSUE THREAD

**Issue by gllms** [gllms/Jottey#8]
- Undo
- Cut
- Copy
- Paste
- Delete

**Comment by milkshakespoon** [comment]
- Redo

**Comment by gllms** [comment]
Do you want to do this issue? Without me suddenly doing it? :grin:

**Comment by gllms** [comment]
Or do you want me to do it?

**Comment by gentleadam** [comment]
Sorry mate. Been busy recently and haven't had a lot of time to spend on this. I'm still keeping an eye on your progress.
